### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by zahek** [coreymwamba/old-opera-notes#1]
The extension idea is nice and probably you will improve it but I can put some my comments here.

-I think the extension button should be on exension bar instead in adress field.
-A plus (+) Extension icon would be nice  instead actual one.
-Also it would be nice if you would be added an option which add notes from web page in context menu 
-Also options page is neede maybe you can add an export-impot option as well later..

**Comment by coreymwamba** [comment]
Have a look now... since Opera has added the sidebar I was able to make some adjustments. I can't currently do the last wish on your list though.
