### ISSUE TITLE
Copy To Note is broken

### ISSUE THREAD

**Issue by coreymwamba** [coreymwamba/old-opera-notes#2]
Steps:
1. Open panel
2. Select text in web page and open context menu
3. Select "Copy To Note"

Expected result:
The selected text should appear as a note

What actually happens:
The selected text doesn't appear as a note unless you close the panel and then open it again.

If anyone can help me fix this, I'd very much appreciate the help!

**Comment by shwetank** [comment]
See https://github.com/coreymwamba/old-opera-notes/pull/3 ... I've gone and fixed it there :)
