### ISSUE TITLE
Port to Firefox

### ISSUE THREAD

**Issue by nt1m** [coreymwamba/old-opera-notes#4]
Firefox supports chrome extensions + opera's sidebar API, it would be nice if you could submit the extension to the Firefox add-on store if possible

**Comment by coreymwamba** [comment]
Wow, I haven't worked on this for ages though... it's very long in the tooth. If you still think it's a good extension, I'll have a look at the Firefox store.

**Comment by coreymwamba** [comment]
Just had a quick look at the Firefox extension API, then tried loading the extension into Firefox. It works, but FF does not ignore the "minimum_opera_version" in the manifest.

**Comment by coreymwamba** [comment]
Okay - I've added it, it's just waiting for review.

**Comment by coreymwamba** [comment]
https://addons.mozilla.org/en-US/firefox/addon/old-opera-notes/

**Comment by nt1m** [comment]
Thanks!
