### ISSUE TITLE
Note Text is Black - Hard to see when using Dark Mode

### ISSUE THREAD

**Issue by rhall0731** [coreymwamba/old-opera-notes#7]
Hi there! Love the extension, thank you for creating it! 

Would it be possible to include an option to make the text in the lower box white? In Dark Mode it looks like this and is hard to read: 

![image](https://user-images.githubusercontent.com/87779185/126540194-6310140c-cf89-4c8f-9e49-678e8112241d.png)

Thanks! :)

**Comment by christales** [comment]
@rhall0731 should be fine now after the latest merge
@coreymwamba not sure how new releases are published with extensions - would simply updating the manifest file do the job?

**Comment by coreymwamba** [comment]
@christales I'm unsure myself—I think there's been a change in submitting as well. I'll check this week.

**Comment by christales** [comment]
@coreymwamba Great! Let me know if you need any help - I love the simplicity of this notepad despite not having seen the original one. There's still a ton of stuff that IMO should be done with the UI & I'll be dropping some PRs every now and again

**Comment by coreymwamba** [comment]
I would absolutely appreciate the help! I built this before Vivaldi got notes.
